<?xml version="1.0" encoding="utf-8"?><Database Name="Salon" Class="DataClassesLinqSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SHANTELE-PC\SQLEXPRESS;Initial Catalog=Salon;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SalonConnectionString" Provider="System.Data.SqlClient" />
</Database>